### ISSUE TITLE
[공유] [대학(원)생 모집] 2019년 2학기 자유학기제 수업지원인력풀(대학생봉사단, 수업지원단) 참가 모집

### ISSUE THREAD

**Issue by unizard** [sejong-rcv/2019.Summer.AIMaker#9]
## SW 중학생 멘토링 
https://www.kofac.re.kr/?mod=document&uid=10822&page_id=2179

![image](https://user-images.githubusercontent.com/11758940/59735173-6e4c8d00-928f-11e9-9511-70a4d2bcb38b.png)

- [모집공고](https://www.kofac.re.kr/download.php?filename=%2Fupload%2Fkboard_attached%2F309%2F201906%2F201906180908351585031.hwp&post_id=10822&file=file1&downurl=http://www.kofac.re.kr/upload/kboard_attached/309/201906/201906180908351585031.hwp)

**Comment by unizard** [comment]
@lini1634 해린아, 공유해준 위의 내용과 메이커스 활동에 대한 활용과 연결해서 고민해보자.

**Comment by lini1634** [comment]
@unizard 넵 교수님 혹시 저희 언제 티타임 가능한가요 ?? 그 날짜 까지 팀원들이랑 의견 맞추고 활동에 대해서 고민해보고 얘기하고 싶어서요!!

**Comment by unizard** [comment]
@unizard 24일 텀플발표전 어때? 교수님이 25일 26일은 제주도 출장이거

**Comment by lini1634** [comment]
@unizard  24일 텀플 발표전에 팀원 중에 한명이 봉사 있다고 해서 28일 1-4시 제외하고 가능하신가요 ?? 1-4시부터는 계절학기 수업 있다고 합니다 !

**Comment by unizard** [comment]
@lini1634 28일 오전은 가능해요? 4시부터는 연구실 행사를 해야 할
